# Generated by Django 3.2.12 on 2022-05-30 09:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_id', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('next_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Feedback Plugin Chart Results',
            },
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('data', models.BinaryField()),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField()),
                ('server', models.ForeignKey(db_column='server_id', on_delete=django.db.models.deletion.PROTECT, to='feedback_plugin.server')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=1000)),
                ('upload', models.ForeignKey(db_column='upload_id', on_delete=django.db.models.deletion.PROTECT, to='feedback_plugin.upload')),
            ],
        ),
        migrations.CreateModel(
            name='ComputedUploadFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('upload', models.ForeignKey(db_column='upload_id', on_delete=django.db.models.deletion.PROTECT, to='feedback_plugin.upload')),
            ],
        ),
        migrations.CreateModel(
            name='ComputedServerFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('server', models.ForeignKey(db_column='server_id', on_delete=django.db.models.deletion.PROTECT, to='feedback_plugin.server')),
            ],
        ),
        migrations.AddIndex(
            model_name='upload',
            index=models.Index(fields=['upload_time', 'server_id'], name='feedback_pl_upload__f79ec0_idx'),
        ),
    ]
