# Generated by Django 3.2.13 on 2022-10-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computedserverfact',
            name='value',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='computeduploadfact',
            name='value',
            field=models.CharField(max_length=1000),
        ),
    ]
