# Generated by Django 4.1.2 on 2022-10-26 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_plugin', '0002_increase_computed_server_fact_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('values', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name_plural': 'Feedback Plugin Chart Results',
            },
        ),
        migrations.DeleteModel(
            name='Charts',
        ),
        migrations.RenameField(
            model_name='computedserverfact',
            old_name='name',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='computeduploadfact',
            old_name='name',
            new_name='key',
        ),
        migrations.CreateModel(
            name='ChartMetadata',
            fields=[
                ('chart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='metadata', serialize=False, to='feedback_plugin.chart')),
                ('computed_start_date', models.DateTimeField(blank=True, null=True)),
                ('computed_end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
