# Generated by Django 4.1.2 on 2022-11-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_plugin', '0003_rename_field_name_to_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('key', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AddIndex(
            model_name='config',
            index=models.Index(fields=['key'], name='feedback_pl_key_b4c61e_idx'),
        ),
    ]
