# Generated by Django 4.1.2 on 2022-11-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_plugin', '0004_create_config_table'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rawdata',
            index=models.Index(fields=['upload_time'], name='feedback_pl_upload__edf031_idx'),
        ),
    ]
