version: '2.1'
services:
  db:
    build:
      context: ../
      args:
        mariadb_version: "${MARIADB_VERSION}"
      dockerfile: docker/mariadb/Dockerfile
    restart: always
    environment:
      - MARIADB_AUTO_UPGRADE='YES'
      - MARIADB_ROOT_PASSWORD
      - DJANGO_DB_NAME
      - DJANGO_DB_USER_NAME
      - DJANGO_DB_USER_PASSWORD
      - MARIADB_MYSQL_LOCALHOST_USER
    healthcheck:
      test: /usr/local/bin/healthcheck.sh --su=mysql --connect --innodb_initialized
      interval: 3s
      timeout: 2s
      retries: 3
    volumes:
      - ${MARIADB_DATADIR}:/var/lib/mysql:Z
      - ${MARIADB_CONFDIR}:/etc/mysql/mariadb.conf.d:Z
  web:
    build:
      context: ../
      args:
        python_version: "${PYTHON_VERSION}"
      dockerfile: docker/app/Dockerfile
    restart: always
    environment:
      - DJANGO_ALLOWED_HOSTS
      - DJANGO_SECRET_KEY
      - DJANGO_DEBUG
      - DJANGO_DB_NAME
      - DJANGO_DB_USER_NAME
      - DJANGO_DB_USER_PASSWORD
      - DJANGO_LOG_LEVEL
    command: gunicorn feedback_plugin.wsgi --bind 0.0.0.0:8000 -w 6 -t 4
                      --capture-output
                      --access-logfile /app/logs/gunicorn-access.log
                      --reload
    volumes:
      # nginx serves the apps static files, share volume
      - static_volume:/app/src/staticfiles:Z
      - ../src/:/app/src/:Z
    depends_on:
      db:
        condition: service_healthy
  nginx:
    build:
      context: ./nginx
      args:
        nginx_version: "${NGINX_VERSION}"
    restart: always
    volumes:
      - static_volume:/home/app/web/staticfiles:Z
    ports:
      - 8000:80
    depends_on:
      - db
      - web

volumes:
  static_volume:
